import { Element } from '../types/chemistry';

export const periodicTable: Element[] = [
  // Period 1
  { symbol: 'H', name: 'Hydrogen', atomicNumber: 1, atomicMass: 1.008, group: 1, period: 1, category: 'nonmetal', electronConfig: '1s¹' },
  { symbol: 'He', name: 'Helium', atomicNumber: 2, atomicMass: 4.003, group: 18, period: 1, category: 'noble-gas', electronConfig: '1s²' },
  
  // Period 2
  { symbol: 'Li', name: 'Lithium', atomicNumber: 3, atomicMass: 6.94, group: 1, period: 2, category: 'alkali-metal', electronConfig: '[He] 2s¹' },
  { symbol: 'Be', name: 'Beryllium', atomicNumber: 4, atomicMass: 9.012, group: 2, period: 2, category: 'alkaline-earth', electronConfig: '[He] 2s²' },
  { symbol: 'B', name: 'Boron', atomicNumber: 5, atomicMass: 10.81, group: 13, period: 2, category: 'metalloid', electronConfig: '[He] 2s² 2p¹' },
  { symbol: 'C', name: 'Carbon', atomicNumber: 6, atomicMass: 12.011, group: 14, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p²' },
  { symbol: 'N', name: 'Nitrogen', atomicNumber: 7, atomicMass: 14.007, group: 15, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p³' },
  { symbol: 'O', name: 'Oxygen', atomicNumber: 8, atomicMass: 15.999, group: 16, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p⁴' },
  { symbol: 'F', name: 'Fluorine', atomicNumber: 9, atomicMass: 18.998, group: 17, period: 2, category: 'halogen', electronConfig: '[He] 2s² 2p⁵' },
  { symbol: 'Ne', name: 'Neon', atomicNumber: 10, atomicMass: 20.180, group: 18, period: 2, category: 'noble-gas', electronConfig: '[He] 2s² 2p⁶' },
  
  // Period 3
  { symbol: 'Na', name: 'Sodium', atomicNumber: 11, atomicMass: 22.990, group: 1, period: 3, category: 'alkali-metal', electronConfig: '[Ne] 3s¹' },
  { symbol: 'Mg', name: 'Magnesium', atomicNumber: 12, atomicMass: 24.305, group: 2, period: 3, category: 'alkaline-earth', electronConfig: '[Ne] 3s²' },
  { symbol: 'Al', name: 'Aluminum', atomicNumber: 13, atomicMass: 26.982, group: 13, period: 3, category: 'post-transition', electronConfig: '[Ne] 3s² 3p¹' },
  { symbol: 'Si', name: 'Silicon', atomicNumber: 14, atomicMass: 28.085, group: 14, period: 3, category: 'metalloid', electronConfig: '[Ne] 3s² 3p²' },
  { symbol: 'P', name: 'Phosphorus', atomicNumber: 15, atomicMass: 30.974, group: 15, period: 3, category: 'nonmetal', electronConfig: '[Ne] 3s² 3p³' },
  { symbol: 'S', name: 'Sulfur', atomicNumber: 16, atomicMass: 32.06, group: 16, period: 3, category: 'nonmetal', electronConfig: '[Ne] 3s² 3p⁴' },
  { symbol: 'Cl', name: 'Chlorine', atomicNumber: 17, atomicMass: 35.45, group: 17, period: 3, category: 'halogen', electronConfig: '[Ne] 3s² 3p⁵' },
  { symbol: 'Ar', name: 'Argon', atomicNumber: 18, atomicMass: 39.948, group: 18, period: 3, category: 'noble-gas', electronConfig: '[Ne] 3s² 3p⁶' },
  
  // Period 4
  { symbol: 'K', name: 'Potassium', atomicNumber: 19, atomicMass: 39.098, group: 1, period: 4, category: 'alkali-metal', electronConfig: '[Ar] 4s¹' },
  { symbol: 'Ca', name: 'Calcium', atomicNumber: 20, atomicMass: 40.078, group: 2, period: 4, category: 'alkaline-earth', electronConfig: '[Ar] 4s²' },
  { symbol: 'Sc', name: 'Scandium', atomicNumber: 21, atomicMass: 44.956, group: 3, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹ 4s²' },
  { symbol: 'Ti', name: 'Titanium', atomicNumber: 22, atomicMass: 47.867, group: 4, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d² 4s²' },
  { symbol: 'V', name: 'Vanadium', atomicNumber: 23, atomicMass: 50.942, group: 5, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d³ 4s²' },
  { symbol: 'Cr', name: 'Chromium', atomicNumber: 24, atomicMass: 51.996, group: 6, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁵ 4s¹' },
  { symbol: 'Mn', name: 'Manganese', atomicNumber: 25, atomicMass: 54.938, group: 7, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁵ 4s²' },
  { symbol: 'Fe', name: 'Iron', atomicNumber: 26, atomicMass: 55.845, group: 8, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁶ 4s²' },
  { symbol: 'Co', name: 'Cobalt', atomicNumber: 27, atomicMass: 58.933, group: 9, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁷ 4s²' },
  { symbol: 'Ni', name: 'Nickel', atomicNumber: 28, atomicMass: 58.693, group: 10, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁸ 4s²' },
  { symbol: 'Cu', name: 'Copper', atomicNumber: 29, atomicMass: 63.546, group: 11, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹⁰ 4s¹' },
  { symbol: 'Zn', name: 'Zinc', atomicNumber: 30, atomicMass: 65.38, group: 12, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹⁰ 4s²' },
  { symbol: 'Ga', name: 'Gallium', atomicNumber: 31, atomicMass: 69.723, group: 13, period: 4, category: 'post-transition', electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹' },
  { symbol: 'Ge', name: 'Germanium', atomicNumber: 32, atomicMass: 72.630, group: 14, period: 4, category: 'metalloid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p²' },
  { symbol: 'As', name: 'Arsenic', atomicNumber: 33, atomicMass: 74.922, group: 15, period: 4, category: 'metalloid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p³' },
  { symbol: 'Se', name: 'Selenium', atomicNumber: 34, atomicMass: 78.971, group: 16, period: 4, category: 'nonmetal', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴' },
  { symbol: 'Br', name: 'Bromine', atomicNumber: 35, atomicMass: 79.904, group: 17, period: 4, category: 'halogen', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵' },
  { symbol: 'Kr', name: 'Krypton', atomicNumber: 36, atomicMass: 83.798, group: 18, period: 4, category: 'noble-gas', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶' },
  
  // Period 5
  { symbol: 'Rb', name: 'Rubidium', atomicNumber: 37, atomicMass: 85.468, group: 1, period: 5, category: 'alkali-metal', electronConfig: '[Kr] 5s¹' },
  { symbol: 'Sr', name: 'Strontium', atomicNumber: 38, atomicMass: 87.62, group: 2, period: 5, category: 'alkaline-earth', electronConfig: '[Kr] 5s²' },
  { symbol: 'Y', name: 'Yttrium', atomicNumber: 39, atomicMass: 88.906, group: 3, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹ 5s²' },
  { symbol: 'Zr', name: 'Zirconium', atomicNumber: 40, atomicMass: 91.224, group: 4, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d² 5s²' },
  { symbol: 'Nb', name: 'Niobium', atomicNumber: 41, atomicMass: 92.906, group: 5, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁴ 5s¹' },
  { symbol: 'Mo', name: 'Molybdenum', atomicNumber: 42, atomicMass: 95.95, group: 6, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁵ 5s¹' },
  { symbol: 'Tc', name: 'Technetium', atomicNumber: 43, atomicMass: 98, group: 7, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁵ 5s²' },
  { symbol: 'Ru', name: 'Ruthenium', atomicNumber: 44, atomicMass: 101.07, group: 8, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁷ 5s¹' },
  { symbol: 'Rh', name: 'Rhodium', atomicNumber: 45, atomicMass: 102.906, group: 9, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁸ 5s¹' },
  { symbol: 'Pd', name: 'Palladium', atomicNumber: 46, atomicMass: 106.42, group: 10, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰' },
  { symbol: 'Ag', name: 'Silver', atomicNumber: 47, atomicMass: 107.868, group: 11, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰ 5s¹' },
  { symbol: 'Cd', name: 'Cadmium', atomicNumber: 48, atomicMass: 112.414, group: 12, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰ 5s²' },
  { symbol: 'In', name: 'Indium', atomicNumber: 49, atomicMass: 114.818, group: 13, period: 5, category: 'post-transition', electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹' },
  { symbol: 'Sn', name: 'Tin', atomicNumber: 50, atomicMass: 118.710, group: 14, period: 5, category: 'post-transition', electronConfig: '[Kr] 4d¹⁰ 5s² 5p²' },
  { symbol: 'Sb', name: 'Antimony', atomicNumber: 51, atomicMass: 121.760, group: 15, period: 5, category: 'metalloid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p³' },
  { symbol: 'Te', name: 'Tellurium', atomicNumber: 52, atomicMass: 127.60, group: 16, period: 5, category: 'metalloid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴' },
  { symbol: 'I', name: 'Iodine', atomicNumber: 53, atomicMass: 126.904, group: 17, period: 5, category: 'halogen', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵' },
  { symbol: 'Xe', name: 'Xenon', atomicNumber: 54, atomicMass: 131.293, group: 18, period: 5, category: 'noble-gas', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶' },
  
  // Period 6
  { symbol: 'Cs', name: 'Cesium', atomicNumber: 55, atomicMass: 132.905, group: 1, period: 6, category: 'alkali-metal', electronConfig: '[Xe] 6s¹' },
  { symbol: 'Ba', name: 'Barium', atomicNumber: 56, atomicMass: 137.327, group: 2, period: 6, category: 'alkaline-earth', electronConfig: '[Xe] 6s²' },
  { symbol: 'La', name: 'Lanthanum', atomicNumber: 57, atomicMass: 138.905, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 5d¹ 6s²' },
  { symbol: 'Ce', name: 'Cerium', atomicNumber: 58, atomicMass: 140.116, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹ 5d¹ 6s²' },
  { symbol: 'Pr', name: 'Praseodymium', atomicNumber: 59, atomicMass: 140.908, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f³ 6s²' },
  { symbol: 'Nd', name: 'Neodymium', atomicNumber: 60, atomicMass: 144.242, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁴ 6s²' },
  { symbol: 'Pm', name: 'Promethium', atomicNumber: 61, atomicMass: 145, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁵ 6s²' },
  { symbol: 'Sm', name: 'Samarium', atomicNumber: 62, atomicMass: 150.36, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁶ 6s²' },
  { symbol: 'Eu', name: 'Europium', atomicNumber: 63, atomicMass: 151.964, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁷ 6s²' },
  { symbol: 'Gd', name: 'Gadolinium', atomicNumber: 64, atomicMass: 157.25, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁷ 5d¹ 6s²' },
  { symbol: 'Tb', name: 'Terbium', atomicNumber: 65, atomicMass: 158.925, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁹ 6s²' },
  { symbol: 'Dy', name: 'Dysprosium', atomicNumber: 66, atomicMass: 162.500, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁰ 6s²' },
  { symbol: 'Ho', name: 'Holmium', atomicNumber: 67, atomicMass: 164.930, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹¹ 6s²' },
  { symbol: 'Er', name: 'Erbium', atomicNumber: 68, atomicMass: 167.259, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹² 6s²' },
  { symbol: 'Tm', name: 'Thulium', atomicNumber: 69, atomicMass: 168.934, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹³ 6s²' },
  { symbol: 'Yb', name: 'Ytterbium', atomicNumber: 70, atomicMass: 173.045, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁴ 6s²' },
  { symbol: 'Lu', name: 'Lutetium', atomicNumber: 71, atomicMass: 174.967, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²' },
  { symbol: 'Hf', name: 'Hafnium', atomicNumber: 72, atomicMass: 178.49, group: 4, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d² 6s²' },
  { symbol: 'Ta', name: 'Tantalum', atomicNumber: 73, atomicMass: 180.948, group: 5, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²' },
  { symbol: 'W', name: 'Tungsten', atomicNumber: 74, atomicMass: 183.84, group: 6, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²' },
  { symbol: 'Re', name: 'Rhenium', atomicNumber: 75, atomicMass: 186.207, group: 7, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²' },
  { symbol: 'Os', name: 'Osmium', atomicNumber: 76, atomicMass: 190.23, group: 8, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²' },
  { symbol: 'Ir', name: 'Iridium', atomicNumber: 77, atomicMass: 192.217, group: 9, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²' },
  { symbol: 'Pt', name: 'Platinum', atomicNumber: 78, atomicMass: 195.084, group: 10, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹' },
  { symbol: 'Au', name: 'Gold', atomicNumber: 79, atomicMass: 196.967, group: 11, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹' },
  { symbol: 'Hg', name: 'Mercury', atomicNumber: 80, atomicMass: 200.592, group: 12, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²' },
  { symbol: 'Tl', name: 'Thallium', atomicNumber: 81, atomicMass: 204.38, group: 13, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹' },
  { symbol: 'Pb', name: 'Lead', atomicNumber: 82, atomicMass: 207.2, group: 14, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²' },
  { symbol: 'Bi', name: 'Bismuth', atomicNumber: 83, atomicMass: 208.980, group: 15, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³' },
  { symbol: 'Po', name: 'Polonium', atomicNumber: 84, atomicMass: 209, group: 16, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴' },
  { symbol: 'At', name: 'Astatine', atomicNumber: 85, atomicMass: 210, group: 17, period: 6, category: 'halogen', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵' },
  { symbol: 'Rn', name: 'Radon', atomicNumber: 86, atomicMass: 222, group: 18, period: 6, category: 'noble-gas', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶' },
  
  // Period 7
  { symbol: 'Fr', name: 'Francium', atomicNumber: 87, atomicMass: 223, group: 1, period: 7, category: 'alkali-metal', electronConfig: '[Rn] 7s¹' },
  { symbol: 'Ra', name: 'Radium', atomicNumber: 88, atomicMass: 226, group: 2, period: 7, category: 'alkaline-earth', electronConfig: '[Rn] 7s²' },
  { symbol: 'Ac', name: 'Actinium', atomicNumber: 89, atomicMass: 227, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 6d¹ 7s²' },
  { symbol: 'Th', name: 'Thorium', atomicNumber: 90, atomicMass: 232.038, period: 7, category: 'actinide', electronConfig: '[Rn] 6d² 7s²' },
  { symbol: 'Pa', name: 'Protactinium', atomicNumber: 91, atomicMass: 231.036, period: 7, category: 'actinide', electronConfig: '[Rn] 5f² 6d¹ 7s²' },
  { symbol: 'U', name: 'Uranium', atomicNumber: 92, atomicMass: 238.029, period: 7, category: 'actinide', electronConfig: '[Rn] 5f³ 6d¹ 7s²' },
  { symbol: 'Np', name: 'Neptunium', atomicNumber: 93, atomicMass: 237, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁴ 6d¹ 7s²' },
  { symbol: 'Pu', name: 'Plutonium', atomicNumber: 94, atomicMass: 244, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁶ 7s²' },
  { symbol: 'Am', name: 'Americium', atomicNumber: 95, atomicMass: 243, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁷ 7s²' },
  { symbol: 'Cm', name: 'Curium', atomicNumber: 96, atomicMass: 247, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁷ 6d¹ 7s²' },
  { symbol: 'Bk', name: 'Berkelium', atomicNumber: 97, atomicMass: 247, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁹ 7s²' },
  { symbol: 'Cf', name: 'Californium', atomicNumber: 98, atomicMass: 251, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁰ 7s²' },
  { symbol: 'Es', name: 'Einsteinium', atomicNumber: 99, atomicMass: 252, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹¹ 7s²' },
  { symbol: 'Fm', name: 'Fermium', atomicNumber: 100, atomicMass: 257, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹² 7s²' },
  { symbol: 'Md', name: 'Mendelevium', atomicNumber: 101, atomicMass: 258, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹³ 7s²' },
  { symbol: 'No', name: 'Nobelium', atomicNumber: 102, atomicMass: 259, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁴ 7s²' },
  { symbol: 'Lr', name: 'Lawrencium', atomicNumber: 103, atomicMass: 266, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹' },
  { symbol: 'Rf', name: 'Rutherfordium', atomicNumber: 104, atomicMass: 267, group: 4, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d² 7s²' },
  { symbol: 'Db', name: 'Dubnium', atomicNumber: 105, atomicMass: 268, group: 5, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²' },
  { symbol: 'Sg', name: 'Seaborgium', atomicNumber: 106, atomicMass: 269, group: 6, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²' },
  { symbol: 'Bh', name: 'Bohrium', atomicNumber: 107, atomicMass: 270, group: 7, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²' },
  { symbol: 'Hs', name: 'Hassium', atomicNumber: 108, atomicMass: 277, group: 8, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²' },
  { symbol: 'Mt', name: 'Meitnerium', atomicNumber: 109, atomicMass: 278, group: 9, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²' },
  { symbol: 'Ds', name: 'Darmstadtium', atomicNumber: 110, atomicMass: 281, group: 10, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s¹' },
  { symbol: 'Rg', name: 'Roentgenium', atomicNumber: 111, atomicMass: 282, group: 11, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹' },
  { symbol: 'Cn', name: 'Copernicium', atomicNumber: 112, atomicMass: 285, group: 12, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²' },
  { symbol: 'Nh', name: 'Nihonium', atomicNumber: 113, atomicMass: 286, group: 13, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹' },
  { symbol: 'Fl', name: 'Flerovium', atomicNumber: 114, atomicMass: 289, group: 14, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²' },
  { symbol: 'Mc', name: 'Moscovium', atomicNumber: 115, atomicMass: 290, group: 15, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³' },
  { symbol: 'Lv', name: 'Livermorium', atomicNumber: 116, atomicMass: 293, group: 16, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴' },
  { symbol: 'Ts', name: 'Tennessine', atomicNumber: 117, atomicMass: 294, group: 17, period: 7, category: 'halogen', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵' },
  { symbol: 'Og', name: 'Oganesson', atomicNumber: 118, atomicMass: 294, group: 18, period: 7, category: 'noble-gas', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶' },
];

export const categoryColors: Record<string, string> = {
  'nonmetal': '#3b82f6',
  'noble-gas': '#8b5cf6',
  'alkali-metal': '#ef4444',
  'alkaline-earth': '#f59e0b',
  'metalloid': '#10b981',
  'halogen': '#14b8a6',
  'transition-metal': '#ec4899',
  'post-transition': '#6366f1',
  'lanthanide': '#f97316',
  'actinide': '#84cc16',
};
